name: CI
on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: "9.0.5"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: test packages
        run: GITHUB_ACTIONS=true pnpm run test -- --reporter=default --reporter=junit --outputFile=../../test-results.xml

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results.xml
          retention-days: 30