name: CI

on:
  push:
    branches:
      - '**'  # Matches every branch
  pull_request:
    branches:
      - master

jobs:
  install-lint-and-test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npx nypm@latest i && cd playground && npx nypm@latest i
      - name: Playground prepare
        run: npm run dev:prepare

      - name: Typecheck
        run: npm run test:types

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Coverage
        uses: codecov/codecov-action@v4
        with:
          # fail_ci_if_error: true # optional (default = false)
          # files: ./coverage1.xml,./coverage2.xml # optional
          # flags: unittests # optional
          # name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          # verbose: true # optional (default = false)

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
