name: CI

on:
  push:
    branches:
      - '**'  # Matches every branch
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npx nypm@latest i
      - name: Playground prepare
        run: npm run dev:prepare

  lint:
    runs-on: ubuntu-latest
    needs: setup  # Ensure this job runs after the setup job
    steps:
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 10
    steps:
      - name: Test
        run: npm run test
