name: CI
on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:
    branches: [master]
jobs:
  setup:
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Playground prepare
        run: npm run dev:prepare

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: npx nypm@latest i

      - name: Lint
        run: npm run lint

    test:
      timeout-minutes: 10
      runs-on: ubuntu-latest
      - name: Test
        run: npm run test
